version: 2.1

executors:
  ubuntu_executor:
    machine:
      image: ubuntu-2004:202111-02

jobs:
  "Build/generate and store artifact":
    executor: ubuntu_executor
    steps:
      - checkout
      - run:
          name: Build
          command:
      - store_artifacts:
          path: your/custom/path
          destination: your_artifact_name

workflows:
  version: 2
  build:
    jobs:
      - Build/generate and store artifact